# Generated by Django 5.2.1 on 2025-07-15 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BondcastRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=10)),
                ('sender_name', models.CharField(help_text='Name of sender (for AI requests)', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('request_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('seen', models.BooleanField(default=False, help_text='Whether the recipient has seen this request')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bondcast_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_bondcast_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bondcast_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='bondcast_re_recipie_66e087_idx'), models.Index(fields=['sender_type', 'sender'], name='bondcast_re_sender__47373a_idx'), models.Index(fields=['created_at'], name='bondcast_re_created_268b92_idx')],
            },
        ),
    ]
