# fly.toml app configuration file generated for bondiver-backend-mvp-personal on 2025-06-07T21:59:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bondiver-backend-mvp-personal'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-1x'
