# fly.toml app configuration file generated for bondiver-backend-mvp on 2025-06-09T13:00:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bondiver-backend-mvp'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
