# Generated by Django 5.2.1 on 2025-06-06 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="audioclip", name="to_user",),
        migrations.RemoveField(model_name="audioclip", name="user",),
        migrations.AddField(
            model_name="audioclip",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_recordings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="audioclip",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_recordings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
