# Generated by Django 5.2.1 on 2025-06-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0002_remove_audioclip_to_user_remove_audioclip_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioclip",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
