# Generated by Django 5.2.1 on 2025-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0003_audioclip_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioclip",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
