# Generated by Django 5.2.1 on 2025-06-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0005_friendship"),
    ]

    operations = [
        migrations.DeleteModel(name="Friendship",),
    ]
