# Generated by Django 5.2.1 on 2025-06-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0006_delete_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioclip",
            name="title",
            field=models.CharField(default="Untitled Recording", max_length=100),
        ),
    ]
