# Generated by Django 5.2.1 on 2025-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0007_audioclip_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioclip",
            name="title",
            field=models.CharField(default="Untitled Recording", max_length=150),
        ),
    ]
