# Generated by Django 5.2.1 on 2025-05-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="firstname",
            field=models.CharField(default="Anonymous", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="lastname",
            field=models.CharField(default="LastName", max_length=20),
            preserve_default=False,
        ),
    ]
