# Generated by Django 5.2.1 on 2025-05-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_firstname_customuser_lastname"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dob",
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
    ]
