# Generated by Django 5.2.1 on 2025-05-19 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "__first__"),
        ("users", "0003_customuser_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(
                related_name="+",
                through="friends.Friendship",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
