# Generated by Django 5.2.1 on 2025-07-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='convo_llm_mode',
            field=models.CharField(default='fteIntro', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_summary',
            field=models.TextField(default=''),
        ),
    ]
